[display]
color-mode = "monochrome"

[page]
'C-k' = '() => pager.load("ddg:")'
'd' = 'halfPageDown'

[external]
copy-cmd = "([ `uname -s` = 'Linux' ] && xclip -selection clipboard $1 || pbcopy $1)"
mailcap = ["${DOTRCDIR}/chawan/mailcap"]
bookmark = "$WP/private-configs/chawan/bookmark.md"
history-file = "$WP/private-configs/chawan/history.uri"
cookie-file = "$WP/private-configs/chawan/cookies.txt"

[buffer]
user-style = '''
/* Underline all links in monochrome color-mode */
@media (monochrome) {
    a[href] { text-decoration: revert !important }
    a[href] { text-decoration-line: underline !important }
}
'''

# Disable css for a bunch of sites
[[siteconf]]
url = 'https://www\.geeksforgeeks\.org/.*'
styling = false
[[siteconf]]
url = 'https://www\.atlassian\.com/.*'
styling = false
