#PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
PS1='[\u@\h \W]\$ '

# Vi mode
set -o vi

# Read the inputrc from the dotrc directory
export INPUTRC="${DOTRCDIR}/bash/inputrc"

# This will force usage of color in ls output
# This was only required for MacOS. Debian already shows colored output for ls.
export CLICOLOR=1

# Update the ls color coding for MacOS
# Linux is unaffected by this as Linux uses LS_COLORS instead.
# directory foreground: cyan (default: blue)
export LSCOLORS='gxfxcxdxbxegedabagacad'

# Don't log consecutive identical commands in bash history
export HISTCONTROL=ignoredups

# Don't add the following colon(:) separated commands are not added in bash
# history
export HISTIGNORE='cl:history'

# Making the history size to 5000. Default is 500.
export HISTSIZE=5000

# The history list is appended to the file named by the value of the HISTFILE
# variable when the shell exits, rather than overwriting the file.
shopt -s histappend

# Export history on every new command
export PROMPT_COMMAND='history -a'

PATH="${DOTRCDIR}/bin:${PATH}"
export PATH

eval "$(fzf --bash)"

# This is used by my custom npm config. Also utilizing this for storing all
# local command line binaries.
PATH=${HOME}/.local/bin:$PATH

# Include Kotlin compiler in the PATH
if [ -d "${HOME}/opt/kotlinc/bin" ]; then
    PATH="${HOME}/opt/kotlinc/bin:${PATH}"
elif [ -d "/opt/kotlinc/bin" ]; then
    PATH="/opt/kotlinc/bin:${PATH}"
fi

# This will make sure that pip user install goes into ~/.local.
# Although this happens automatically on Linux, this is required for MacOS
export PYTHONUSERBASE=~/.local

# fzf custom completions
if declare -F _fzf_setup_completion >/dev/null; then
    _fzf_setup_completion path trash
    _fzf_setup_completion path play
fi

# Enable globstar
shopt -s globstar

# If neovim is available, set it as the EDITOR
if command -v nvim 1>/dev/null 2>&1; then
    export EDITOR='nvim'
fi

bind -m vi-insert -x '"\C-h": run-help'

export WP="$HOME/workspaces/personal"
export TODO_PATH="$WP/notes/todo.txt"

if [ -f ${DOTRCDIR}/bash/bash_aliases ]; then
    . ${DOTRCDIR}/bash/bash_aliases
fi

if [ -f ${DOTRCDIR}/bash/bash_functions ]; then
    . ${DOTRCDIR}/bash/bash_functions
fi

for config in "${ADDITIONAL_BASH_CONFIGS[@]}"
do
    if [ -f "$config" ]; then
        . "$config"
    else
        echo WARNING: $config does not exist.
    fi
done

# Print todo once after launch
print_todo
