PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '

# Vi mode
set -o vi

# Read the inputrc from the dotrc directory
export INPUTRC="${DOTRCDIR}/bash/inputrc"

# This will force usage of color in ls output
# This was only required for MacOS. Debian already shows colored output for ls.
export CLICOLOR=1

# Update the ls color coding for MacOS
# Linux is unaffected by this as Linux uses LS_COLORS instead.
# directory foreground: cyan (default: blue)
export LSCOLORS='gxfxcxdxbxegedabagacad'

# Don't add the following colon(:) separated commands are not added in bash
# history
export HISTIGNORE='cl:history'

# PATH
## ruby
if [ -d ${HOME}/.gem/ruby/3.0.0/bin ]; then
    PATH="${HOME}/.gem/ruby/3.0.0/bin:${PATH}"
elif [ -d ${HOME}/.gem/ruby/2.7.0/bin ]; then
    PATH="${HOME}/.gem/ruby/2.7.0/bin:${PATH}"
elif [ -d ${HOME}/.gem/ruby/2.5.0/bin ]; then
    PATH="${HOME}/.gem/ruby/2.5.0/bin:${PATH}"
fi
test -d /usr/local/opt/ruby/bin && PATH="/usr/local/opt/ruby/bin:${PATH}"

PATH="${DOTRCDIR}/bin:${PATH}"
export PATH

# Load fzf completion on Debian`
test -f /usr/share/doc/fzf/examples/key-bindings.bash && source /usr/share/doc/fzf/examples/key-bindings.bash
test -f /usr/share/bash-completion/completions/fzf && source /usr/share/bash-completion/completions/fzf

# Load fzf completion on MacOS
test -f /usr/local/opt/fzf/shell/completion.bash && source /usr/local/opt/fzf/shell/completion.bash

# This is used by my custom npm config. Also utilizing this for storing all
# local command line binaries.
PATH=${HOME}/.local/bin:$PATH

# Include Kotlin compiler in the PATH
if [ -d "${HOME}/opt/kotlinc/bin" ]; then
    PATH="${HOME}/opt/kotlinc/bin:${PATH}"
elif [ -d "/opt/kotlinc/bin" ]; then
    PATH="/opt/kotlinc/bin:${PATH}"
fi

# This will make sure that pip user install goes into ~/.local.
# Although this happens automatically on Linux, this is required for MacOS
export PYTHONUSERBASE=~/.local

# fzf custom completions
_fzf_setup_completion path trash
_fzf_setup_completion path play
