#!/usr/bin/env bash

# nvim
alias vi='nvim'
alias vimdiff='nvim -d'

# cd
alias cdwp='cd $HOME/workspaces/personal/'
alias cdws='cd $HOME/workspaces/study/'
alias cdwpn='cd $HOME/workspaces/personal/notes'
alias cdwpd='cd $HOME/workspaces/personal/dotfiles'
alias cdwppc='cd $HOME/workspaces/personal/private-configs'
alias cdwpts='cd $HOME/workspaces/personal/tmux-scripts'

# ls
alias ll='ls -lrth'

# tmux launch scripts
alias th='$HOME/workspaces/personal/tmux-scripts/home-tmux.sh'
alias tw='$HOME/workspaces/personal/tmux-scripts/work-tmux.sh'

# Jekyll
alias js='bundle exec jekyll serve'

# Git
alias gstatus='git status'
alias gbranch='git branch'
alias gadd='git add'
alias gdiff='git diff'
alias glog='git log'
alias gc='git commit'
alias gcu='git commit -m "updated"'
alias gptm='git push origin master'
alias gpfm='git pull origin master'

gaf() {
    local file
    file=$(git status -s|grep '^.[^ ]'|fzf)
    if [ $? -ne 0 ]; then
        return
    fi
    echo Generating diff for selection: $file
    echo

    status=$(echo ${file}|awk '{print $1}')
    file=$(echo ${file}|awk '{print $2}')

    if [ $status = "??" ]; then
        more "$file"
    else
        git diff "$file"
    fi

    echo
    read -p "Add to index? " choice
    if [ "$choice" = 'y' ]; then
        git add "$file"
        echo Added $file to index.
    else
        echo Aborting.
    fi
}

# Unstages a file but does not revert the changes
gresethead() {
    git diff --name-only --cached|fzf|xargs git reset HEAD
}

gsetconfigp() {
    git config user.name "Subhadip Ghosh"
    git config user.email "subhadipghosh11@gmail.com"

    echo Now you may rewrite the commit with new author info!
}

# Maven
alias mvn-clean-install-skiptests='mvn clean install -DskipTests'
alias mvn-install-skiptests='mvn install -DskipTests'
alias mvn-package-skiptests='mvn package -DskipTests'

# Pandoc
alias pandoc-convert-doc="pandoc \
                            -V geometry:margin=0.8in \
                            -V fontsize:10pt \
                            -V mainfont='DejaVu Serif' \
                            -V monofont='DejaVu Sans Mono' \
                            -V urlcolor=blue \
                            -V toccolor=NavyBlue \
                            -s \
                            -N \
                            --toc \
                            -f markdown-implicit_figures \
                            --pdf-engine=xelatex"
alias pandoc-convert-resume="pandoc \
                                -V geometry:margin=0.8in \
                                -V mainfont='DejaVu Serif' \
                                -V monofont='DejaVu Sans Mono' \
                                -V urlcolor=blue \
                                -s \
                                -f markdown \
                                --pdf-engine=xelatex"

alias pandoc-convert-doc-with-code="pandoc \
                                -V geometry:margin=0.8in \
                                -V mainfont='DejaVu Serif' \
                                -V monofont='DejaVu Sans Mono' \
                                -V urlcolor=blue \
                                -N \
                                --template eisvogel \
                                --listings"
alias pandoc-convert-slides-pdf='pandoc -s -V colortheme:beaver -V theme:Szeged -t beamer'
alias pandoc-convert-slides-html='pandoc -s --webtex -i -t slidy'
alias pandoc-convert-mediawiki='pandoc -f markdown-implicit_figures -t mediawiki'
alias pandoc-convert-from-mediawiki='pandoc -f mediawiki -t markdown'

# Kubernetes
case $OSTYPE in
    linux*) alias minikube-start='minikube start --driver=kvm2';;
    darwin*) alias minikube-start="minikube start --driver=hyperkit --hyperkit-vpnkit-sock=/Users/${USER}/Library/Containers/com.docker.docker/Data/vpnkit.eth.sock";;
esac

# Open
which xdg-open 1>/dev/null && alias open='xdg-open 2>/dev/null'

# Search and open
so() {
    local file
    file=$(fzf)
    if [ $? -ne 0 ]; then
        return
    fi
    echo "Opening ${file}"
    open "${file}"
}

# Search and edit
se() {
    local file
    file=$(fzf)
    if [ $? -ne 0 ]; then
        return
    fi
    echo "Editing ${file}"
    vi "${file}"
}

# Reload bashrc/bash_profile
rb() {
    case "$(uname -s)" in
        Linux*)     . ~/.bashrc;;
        Darwin*)    . ~/.bash_profile;;
        *)          echo "Unknown OS";;
    esac
    echo "Reloaded bash configuration"
}

# Docker
alias dps='docker ps'
alias dpsall='docker ps -all'

# Misc
alias newsboat="newsboat -u $HOME/workspaces/personal/private-configs/newsboat/urls -C ${DOTRCDIR}/newsboat/config"
alias podboat="podboat -C ${DOTRCDIR}/newsboat/config"

alias cq="cal -3"

alias cl="clear"

alias upc="update-personal-config"
